install:
 - mvn clean
script:
 - mvn -B -fae -Dserver.version=$SERVER_VERSION -Dtest=PublisherResponseTest -DfailIfNoTests=false install
 - cat /home/travis/build/resteasy/Resteasy/testsuite/integration-tests/target/surefire-reports/org.jboss.resteasy.test.response.PublisherResponseTest-output.txt

language: java
jdk:
  - oraclejdk8
env:
  - SERVER_VERSION=10.1.0.Final
  - SERVER_VERSION=10.0.0.Final
  - SERVER_VERSION=11.0.0.CR1
cache:
 directories:
  - $HOME/.m2
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
    - "sudo unzip -j -o  travis-libs/jce_policy-8.zip *.jar -d $JAVA_HOME/jre/lib/security"
