install:
 - mvn -B clean; java -version
script:
 - travis_wait 60 mvn -B -Ptravis,jboss-repository -fae -Dserver.version=$SERVER_VERSION ${ELYTRON:+-Delytron} install

language: java
jdk:
  - openjdk8
  - openjdk11
env:
  - SERVER_VERSION=15.0.0.Final
  - SERVER_VERSION=16.0.0.Final
  - SERVER_VERSION=17.0.0.Final
  - SERVER_VERSION=17.0.0.Final ELYTRON=true
jobs:
  exclude:
    - jdk: openjdk11
      env: SERVER_VERSION=17.0.0.Final ELYTRON=true
  include:
    - stage: "javadoc"
      script: mvn -B -Pjboss-repository -DskipTests install && mvn -B -Dmaven.javadoc.skip=false javadoc:javadoc
      jdk: openjdk8
      env: SERVER_VERSION=17.0.0.Final
    - stage: "javadoc"
      script: mvn -B -Pjboss-repository -DskipTests install && mvn -B -Dmaven.javadoc.skip=false javadoc:javadoc
      jdk: oraclejdk11
      env: SERVER_VERSION=17.0.0.Final
addons:
  hosts:
    - localhost.localdomain
##cache:
# directories:
#  - $HOME/.m2
