install:
 - mvn clean; java -version
script:
 - travis_wait 60 mvn -B -Ptravis -fae -Dserver.version=$SERVER_VERSION install

language: java
jdk:
  - oraclejdk11
env:
  - SERVER_VERSION=14.0.0.Final
  - SERVER_VERSION=15.0.0.Final
jobs:
  include:
    - stage: "javadoc"
      script: mvn -B -DskipTests install && mvn -B -Dmaven.javadoc.skip=false javadoc:javadoc
      jdk: oraclejdk11
      env: SERVER_VERSION=15.0.0.Final
