install:
 - mvn clean
script:
 - mvn -B -fae -Dserver.version=$SERVER_VERSION install

language: java
jdk:
  - openjdk8
  - openjdk11
env:
  - SERVER_VERSION=12.0.0.Final
  - SERVER_VERSION=13.0.0.Final
  - SERVER_VERSION=14.0.0.Final
matrix:
  exclude:
    - jdk: oraclejdk11
      env: SERVER_VERSION=12.0.0.Final
    - jdk: oraclejdk11
      env: SERVER_VERSION=13.0.0.Final
#cache:
# directories:
#  - $HOME/.m2
addons:
  apt:
    packages:
      - java-1.8.0-openjdk
