//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-04/09/2009 09:05 AM(mockbuild)-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.10.20 at 02:18:38 PM CEST
//

package org.jboss.resteasy.test.providers.multipart.resource;


import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "getFileRequest")
public class XOPMultipartProxyGetFileRequest {

   private List<XOPMultipartProxyFileProperty> properties;
   @XmlAttribute
   private String sessionId;
   @XmlAttribute
   private String dir;
   @XmlAttribute
   private String fileName;

   public XOPMultipartProxyGetFileRequest() {
      super();
   }

   public XOPMultipartProxyGetFileRequest(final String sessionId, final String dirName, final String fileName) {
      this.sessionId = sessionId;
      this.dir = dirName;
      this.fileName = fileName;
   }

   public XOPMultipartProxyGetFileRequest(final String sessionId, final String dirName, final String fileName, final List<XOPMultipartProxyFileProperty> properties) {
      this.sessionId = sessionId;
      this.dir = dirName;
      this.fileName = fileName;
      this.properties = properties;
   }

   /**
    * Gets the value of the properties property.
    *
    * <p>
    * This accessor method returns a reference to the live list, not a
    * snapshot. Therefore any modification you make to the returned list will
    * be present inside the JAXB object. This is why there is not a
    * <CODE>set</CODE> method for the properties property.
    *
    * <p>
    * For example, to add a new item, do as follows:
    *
    * <pre>
    * getProperties().add(newItem);
    * </pre>
    *
    *
    * <p>
    * Objects of the following type(s) are allowed in the list
    * {@link FileProperty }
    *
    *
    */
   public List<XOPMultipartProxyFileProperty> getProperties() {
      if (properties == null) {
         properties = new ArrayList<XOPMultipartProxyFileProperty>();
      }
      return this.properties;
   }

   /**
    * Gets the value of the sessionId property.
    *
    * @return possible object is {@link String }
    *
    */
   public String getSessionId() {
      return sessionId;
   }

   /**
    * Sets the value of the sessionId property.
    *
    * @param value
    *            allowed object is {@link String }
    *
    */
   public void setSessionId(String value) {
      this.sessionId = value;
   }

   /**
    * Gets the value of the dir property.
    *
    * @return possible object is {@link String }
    *
    */
   public String getDir() {
      return dir;
   }

   /**
    * Sets the value of the dir property.
    *
    * @param value
    *            allowed object is {@link String }
    *
    */
   public void setDir(String value) {
      this.dir = value;
   }

   /**
    * Gets the value of the fileName property.
    *
    * @return possible object is {@link String }
    *
    */
   public String getFileName() {
      return fileName;
   }

   /**
    * Sets the value of the fileName property.
    *
    * @param value
    *            allowed object is {@link String }
    *
    */
   public void setFileName(String value) {
      this.fileName = value;
   }
}
