== Overview

Originally released in 2009, RESTEasy has tracked and implemented a series of official specifications that provide a Java API for RESTful Web Services over the HTTP protocol: 

[cols="1,1", frame="topbot", options="header"]
|===
| RESTEasy version
| Specification


|6.1+
|https://jakarta.ee/specifications/restful-ws/3.1/jakarta-restful-ws-spec-3.1.html[Jakarta RESTful Web Services 3.1]

|6.0
|https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html[Jakarta RESTful Web Services 3.0]

|3.5+
|https://jakarta.ee/specifications/restful-ws/2.1/restful-ws-spec-2.1.html[Jakarta RESTful Web Services 2.1]

|3+
|https://jcp.org/en/jsr/detail?id=339[JAX-RS 2.0]

|2+
|https://download.oracle.com/otndocs/jcp/jaxrs-1.0-fr-eval-oth-JSpec/[JAX-RS 1.0]
|===

JAX-RS 1.0 (https://download.oracle.com/otndocs/jcp/jaxrs-1.0-fr-eval-oth-JSpec/[JSR-311]), JAX-RS 2.0 (https://jcp.org/en/jsr/detail?id=339[JSR-339]), and JAX-RS 2.1 (https://jcp.org/en/jsr/detail?id=370[JSR-370]) are https://jcp.org/en/procedures/overview[Java Community Process (JCP)] specifications.
In 2017, the Java Enterprise Edition (Java EE) specifications, including JAX-RS, were transferred to the Eclipse Foundation (https://blogs.eclipse.org/post/mike-milinkovich/java-ee-moves-eclipse-foundation[
Java EE Moves to the Eclipse Foundation]), Java EE became Jakarta Enterprise Edition, and new governing committees under the umbrella of the https://projects.eclipse.org/proposals/eclipse-jakarta-ee-platform[Eclipse Jakarta EE Platform] were constituted.
For JAX-RS, the specifications are provided by the https://jakarta.ee/specifications/restful-ws/[Jakarta RESTful Web Services] committee. The first specification released under the authority of Jakarta RESTful Web Services was https://jakarta.ee/specifications/restful-ws/2.1/[Jakarta RESTful Web Services 2.1], that being essentially identical to JAX-RS 2.1. 

RESTEasy is a portable implementation of these specifications which can run in any Servlet container.
Tighter integration with the WildFly application server is also available to make the user experience nicer in that environment.
RESTEasy also comes with additional features on top of the plain old specifications. 

[NOTE]
====
References in this document to JAX-RS refer to the {spec-name} unless otherwise noted.
====