//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.25 at 10:14:22 AM EDT 
//


package org.example.b.test;

import org.example.a.testcanonical.TestBase;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TestExtends complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestExtends">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/a/TestCanonical}TestBase">
 *       &lt;sequence>
 *         &lt;element name="someMoreEl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="element2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestExtends", propOrder = {
    "someMoreEl",
    "element2"
})
public class TestExtends
    extends TestBase
{

    @XmlElement(required = true)
    protected String someMoreEl;
    @XmlElement(required = true)
    protected String element2;

    /**
     * Gets the value of the someMoreEl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSomeMoreEl() {
        return someMoreEl;
    }

    /**
     * Sets the value of the someMoreEl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSomeMoreEl(String value) {
        this.someMoreEl = value;
    }

    /**
     * Gets the value of the element2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElement2() {
        return element2;
    }

    /**
     * Sets the value of the element2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElement2(String value) {
        this.element2 = value;
    }

}
