# This workflow is for a nightly run against WildFly upstream

name: Manual RESTEasy Build

on:
  workflow_dispatch:
    inputs:
      os:
        description: "Runner OS"
        required: true
        default: "ubuntu-latest"
        type: string
      javaVersion:
        description: "Java Version"
        required: true
        default: "17"
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ inputs.javaVersion }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.javaVersion }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build on ${{ inputs.os }} with Java ${{ inputs.javaVersion }}
        run: mvn clean install '-Pjakarta-staging'
      - name: Upload surefire reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: surefire-reports
          path: '**/surefire-reports/*'
      - name: Upload server logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: server-logs
          path: '**/*.log'
