# This workflow is for a nightly run against WildFly upstream

name: Manual WildFly Test Build

on:
  workflow_dispatch:
    inputs:
      os:
        description: "Runner OS"
        required: true
        default: "ubuntu-latest"
        type: string
      javaVersion:
        description: "Java Version"
        required: true
        default: "17"
        type: string
      wildfly-branch:
        description: "WildFly Branch"
        required: true
        default: "main"
        type: string
      wildfly-repo:
        description: "WildFly Repository"
        required: true
        default: "wildfly/wildfly"
        type: string

env:
  MVN_ARGS: '-V -B'

jobs:
  wildfly-build:
    uses: wildfly/wildfly/.github/workflows/shared-wildfly-build.yml@main
    with:
      wildfly-branch: ${{ inputs.wildfly-branch }}
      wildfly-repo: ${{ inputs.wildfly-repo }}

  resteasy-build:
    runs-on: ${{ inputs.os }}
    needs: wildfly-build

    steps:
      - uses: actions/checkout@v7
      - uses: actions/download-artifact@v8
        id: download-m2
        with:
          name: wildfly-maven-repository
          path: .
      - name: Extract Maven Repo
        shell: bash
        run: |
          tar -xzf wildfly-maven-repository.tar.gz -C ~
      - name: Set up JDK ${{ inputs.javaVersion }}
        uses: actions/setup-java@v5.6.0
        with:
          java-version: ${{ inputs.javaVersion }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Set up JDK 25
        uses: actions/setup-java@v5.6.0
        with:
          java-version: 25
          distribution: 'temurin'
          cache: 'maven'
      - name: Build on ${{ inputs.os }} with Java ${{ inputs.javaVersion }}
        run: ./mvnw ${{ env.MVN_ARGS }} clean install '-Dserver.version=${{needs.wildfly-build.outputs.wildfly-version}}' '-Dtest.java.home=${{ env[format('JAVA_HOME_{0}_X64', inputs.javaVersion)] }}'
      - name: Upload test logs for failed run
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: failure-report
          path: |
            **/surefire-reports/**
            **/failsafe-reports/**
            **/*.log
