# This workflow will build a Java project with Maven
# For more information see: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Build and Test RESTEasy

on:
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/maven.yml'
      - '**/pom.xml'
      - 'providers/**'
      - '!docbook/pom.xml'
      - '!distribution/pom.xml'
      - 'resteasy-cdi/**'
      - 'resteasy-client/**'
      - 'resteasy-client-api/**'
      - 'resteasy-client-utils/**'
      - 'resteasy-core/**'
      - 'resteasy-core-spi/**'
      - 'resteasy-jsapi/**'
      - 'resteasy-links/**'
      - 'resteasy-reactor/**'
      - 'resteasy-rxjava2/**'
      - 'resteasy-servlet-initializer/**'
      - 'resteasy-stats/**'
      - 'resteasy-wadl/**'
      - 'resteasy-wadl-undertow-connector/**'
      - 'security/**'
      - 'server-adapters/**'
      - 'testsuite/**'
      - '!testsuite/cloud-tests/**'
      - 'wildfly/**'
  schedule:
    - cron: '0 0 * * *' # Every day at 00:00 UTC

# Only run the latest job
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  MVN_ARGS: '-V -B -fae'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v7
      - name: Set up JDKs
        uses: actions/setup-java@v5.6.0
        with:
          distribution: 'temurin'
          cache: 'maven'
          # Please note the order here of having 25 last as that is the version we want to compile with
          java-version: |
            17
            21
            26
            25
      - name: Build and Test on ${{ matrix.os }} - Java 25
        run: ./mvnw ${{ env.MVN_ARGS }} clean install
      - name: Build and Test on ${{ matrix.os }} - Java 26
        run: ./mvnw ${{ env.MVN_ARGS }} verify '-Dtest.java.home=${{env.JAVA_HOME_26_X64}}${{env.JAVA_HOME_26_ARM64}}' '-Dtest.report.dir=java26'
      - name: Build and Test on ${{ matrix.os }} - Java 21
        run: ./mvnw ${{ env.MVN_ARGS }} verify '-Dtest.java.home=${{env.JAVA_HOME_21_X64}}${{env.JAVA_HOME_21_ARM64}}' '-Dtest.report.dir=java21'
      - name: Build and Test on ${{ matrix.os }} - Java 17
        run: ./mvnw ${{ env.MVN_ARGS }} verify '-Dtest.java.home=${{env.JAVA_HOME_17_X64}}${{env.JAVA_HOME_17_ARM64}}' '-Dtest.report.dir=java17'
      - name: Upload test logs for failed run
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: failure-report-${{ matrix.os }}
          path: |
            **/surefire-reports/**
            **/failsafe-reports/**
            **/*.log

  additional-profiles:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        profile:
          - '-Denhanced.cdi.disabled'

    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK 25
        uses: actions/setup-java@v5.6.0
        with:
          java-version: 25
          distribution: 'temurin'
          cache: 'maven'
      - name: Test with ${{ matrix.profile }} - JDK 25
        run:  |
          ./mvnw ${{ env.MVN_ARGS }} clean install -DskipTests
          cd testsuite
          mvn ${{ env.MVN_ARGS }} verify ${{ matrix.profile }}
      - name: Upload test logs for failed run
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: failure-reports${{ matrix.profile }}
          path: |
            **/surefire-reports/**
            **/failsafe-reports/**
            **/*.log

  build-java-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK 25
        uses: actions/setup-java@v5.6.0
        with:
          java-version: 25
          distribution: 'temurin'
          cache: 'maven'
      - name: Build Java Docs with Java 25
        run: |
          mvn ${{ env.MVN_ARGS }} clean install -DskipTests
          mvn ${{ env.MVN_ARGS }} site -DskipTests -Dmpir.skip=true
