# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Jakarta REST TCK

on:
  push:
    branches:
      - 'main'
    paths:
      - 'pom.xml'
      - 'providers/**'
      - 'resteasy-bom/**'
      - 'resteasy-cdi/**'
      - 'resteasy-client/**'
      - 'resteasy-client-api/**'
      - 'resteasy-client-utils/**'
      - 'resteasy-core/**'
      - 'resteasy-core-spi/**'
      - 'resteasy-dependencies-bom/**'
      - 'resteasy-security/**'
      - 'server-adapters/resteasy-undertow-cdi/**'
      - 'wildfly/**'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/resteasy-tck.yml'
      - 'pom.xml'
      - 'providers/**'
      - 'resteasy-bom/**'
      - 'resteasy-cdi/**'
      - 'resteasy-client/**'
      - 'resteasy-client-api/**'
      - 'resteasy-client-utils/**'
      - 'resteasy-core/**'
      - 'resteasy-core-spi/**'
      - 'resteasy-dependencies-bom/**'
      - 'resteasy-security/**'
      - 'server-adapters/resteasy-undertow-cdi/**'
      - 'wildfly/**'

  schedule:
    - cron: '0 0 * * *' # Every day at 00:00 UTC
  workflow_dispatch:
    inputs:
      os:
        description: "Runner OS"
        required: true
        default: "ubuntu-latest"
        type: string
      javaVersion:
        description: "Java Version"
        required: true
        default: "17"
        type: string

# Only run the latest job
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  MVN_ARGS: '-V -B -fae'

jobs:
  run-tck:

    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout RESTEasy
        uses: actions/checkout@v7
        with:
          path: resteasy
      - name: Checkout RESTEasy TCK Runner
        uses: actions/checkout@v7
        with:
          repository: resteasy/resteasy-tck-runner
          path: resteasy-tck-runner
      - name: Set up JDKs
        uses: actions/setup-java@v5.6.0
        with:
          distribution: 'temurin'
          cache: 'maven'
          # Please note the order here of having 25 last as that is the version we want to compile with
          java-version: |
            17
            21
            25
      - name: Build RESTEasy
        id: resteasy-build
        run:  |
          cd resteasy
          ./mvnw ${{ env.MVN_ARGS }} clean install -DskipTests
          RESTEASY_VERSION="$(mvn -B help:evaluate -Dexpression=project.version -DforceStdout -q)"
          echo "RESTEASY_VERSION=$RESTEASY_VERSION"
          echo "RESTEASY_VERSION=$RESTEASY_VERSION" >> "$GITHUB_OUTPUT"
      - name: Run the Jakarta REST TCK - Java 25
        run:  |
          echo "RESTEASY_VERSION=${{ steps.resteasy-build.outputs.RESTEASY_VERSION }}"
          cd resteasy-tck-runner
          mvn ${{ env.MVN_ARGS }} clean verify -Dtck.debug.log=true -Dversion.org.jboss.resteasy="${{ steps.resteasy-build.outputs.RESTEASY_VERSION }}"
      - name: Run the Jakarta REST TCK - Java 21
        run:  |
          echo "RESTEASY_VERSION=${{ steps.resteasy-build.outputs.RESTEASY_VERSION }}"
          cd resteasy-tck-runner
          mvn ${{ env.MVN_ARGS }} verify -Dtck.debug.log=true -Dversion.org.jboss.resteasy="${{ steps.resteasy-build.outputs.RESTEASY_VERSION }}" -Djvm="${{env.JAVA_HOME_21_X64}}/bin/java"
      - name: Run the Jakarta REST TCK - Java 17
        run:  |
          echo "RESTEASY_VERSION=${{ steps.resteasy-build.outputs.RESTEASY_VERSION }}"
          cd resteasy-tck-runner
          mvn ${{ env.MVN_ARGS }} verify -Dtck.debug.log=true -Dversion.org.jboss.resteasy="${{ steps.resteasy-build.outputs.RESTEASY_VERSION }}" -Djvm="${{env.JAVA_HOME_17_X64}}/bin/java"
      - name: Upload test logs for failed run
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: failure-report
          path: |
            **/surefire-reports/**
            **/failsafe-reports/**
            **/*.log
