# A workflow that can be called from other workflows as a way to build a SNAPSHOT of RESTEasy for testing purposes. This
# will attach an archive named "resteasy-maven-repository.tar.gz" which can be downloaded and extracted to use the
# SNAPSHOT dependencies.
#
# An output setting of "resteasy-version" is set with the version of the SNAPSHOT dependencies.
#
# Two input parameters can be set. The parameter resteasy-branch is used to control which branch you'd like a build of.
# The default branch is "main". The parameter resteasy-repo allows you to override the repository used. The default for
# this parameter is "resteasy/resteasy".
#
# Example Usage:
#
# jobs:
#   resteasy-build:
#     uses: resteasy/resteasy/.github/workflows/shared-resteasy-build.yml@main
#     with:
#       resteasy-branch: ${{ inputs.resteasy-branch }}
#       resteasy-repo: ${{ inputs.resteasy-repo }}
#
#   custom-build:
#    runs-on: ubuntu-latest
#    needs: resteasy-build
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/download-artifact@v3
#        with:
#          name: resteasy-maven-repository
#          path: .
#      - name: Extract Maven Repo
#        shell: bash
#        run: |
#          tar -xzf resteasy-maven-repository.tar.gz -C ~
#      - name: Set up JDK ${{ inputs.javaVersion }}
#        uses: actions/setup-java@v4
#        with:
#          java-version: 17
#          distribution: 'temurin'
#          cache: 'maven'
#      - name: Build on Linux with Java 17 using RESTEasy ${{ needs.resteasy-build.outputs.resteasy-version }}
#        run: mvn clean verify '-Dversion.dev.resteasy=${{ needs.resteasy-build.outputs.resteasy-version }}'

name: Build RESTEasy Upstream

on:
  workflow_call:
    outputs:
      resteasy-version:
        description: "The version of RESTEasy that was built"
        value: ${{ jobs.resteasy-build.outputs.resteasy-version }}
    inputs:
      resteasy-branch:
        description: "RESTEasy Branch"
        required: true
        default: "main"
        type: string
      resteasy-repo:
        description: "RESTEasy Repository"
        required: true
        default: "resteasy/resteasy"
        type: string

jobs:
  resteasy-build:
    runs-on: ubuntu-latest
    outputs:
      resteasy-version: ${{ steps.version.outputs.resteasy-version }}
    steps:
      - name: Checkout RESTEasy
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.resteasy-repo }}
          ref: ${{ inputs.resteasy-branch }}
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Build RESTEasy
        run: mvn clean install -DskipTests -Dcheckstyle.skip=true -Denforcer.skip=true -DskipFormatting=true
      - id: version
        run: echo "resteasy-version=$(mvn -B help:evaluate -Dexpression=project.version -DforceStdout -q)" >> $GITHUB_OUTPUT
      - name: Archive the repository
        run:  |
          cd ~
          find ./.m2/repository -type d -name "*SNAPSHOT" -print0 | xargs -0 tar -czf ~/resteasy-maven-repository.tar.gz
      - uses: actions/upload-artifact@v4
        with:
          name: resteasy-maven-repository
          path: ~/resteasy-maven-repository.tar.gz
          retention-days: 5
