# This workflow is for a nightly run against WildFly upstream

name: WildFly Test Build

on:
  push:
    branches:
      - 'main'
    paths:
      - 'pom.xml'
      - 'providers/**'
      - 'resteasy-bom/**'
      - 'resteasy-cdi/**'
      - 'resteasy-client/**'
      - 'resteasy-client-api/**'
      - 'resteasy-client-utils/**'
      - 'resteasy-core/**'
      - 'resteasy-core-spi/**'
      - 'resteasy-dependencies-bom/**'
      - 'testsuite/arquillian-utils/**'
      - 'testsuite/integration-tests/**'
      - 'wildfly/**'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/wildfly-build.yml'
      - 'testsuite/integration-tests/**'
  schedule:
    - cron: '0 0 * * *' # Every day at 00:00 UTC

# Only run the latest job and cancel previous ones
concurrency:
  group: '${{ github.ref || github.run_id }}'
  cancel-in-progress: true

env:
  MVN_ARGS: '-V -B -fae'

jobs:

  resteasy-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v7
      - uses: wildfly-extras/wildfly-nightly-download@v1
        id: wildfly-nightly
      - name: Set up JDKs
        uses: actions/setup-java@v5.7.0
        with:
          distribution: 'temurin'
          cache: 'maven'
          # Please note the order here of having 25 last as that is the version we want to compile with
          java-version: |
            17
            21
            26
            25
      - name: Build RESTEasy
        run: |
          ./mvnw ${{ env.MVN_ARGS }} clean install -DskipTests '-Dserver.version=${{steps.wildfly-nightly.outputs.wildfly-version}}'
      - name: Test on ${{ matrix.os }} WildFly ${{steps.wildfly-nightly.outputs.wildfly-version}} - Java 25
        run: |
          cd testsuite/integration-tests
          mvn ${{ env.MVN_ARGS }} verify
      - name: Test on ${{ matrix.os }} WildFly ${{steps.wildfly-nightly.outputs.wildfly-version}} - Java 26
        run:  |
          cd testsuite/integration-tests
          mvn ${{ env.MVN_ARGS }} verify '-Dtest.java.home=${{env.JAVA_HOME_26_X64}}${{env.JAVA_HOME_26_ARM64}}' '-Dversion.org.wildfly=${{steps.wildfly-nightly.outputs.wildfly-version}}' '-Dtest.report.dir=java26'
      - name: Test on ${{ matrix.os }} WildFly ${{steps.wildfly-nightly.outputs.wildfly-version}} - Java 21
        run:  |
          cd testsuite/integration-tests
          mvn ${{ env.MVN_ARGS }} verify '-Dtest.java.home=${{env.JAVA_HOME_21_X64}}${{env.JAVA_HOME_21_ARM64}}' '-Dversion.org.wildfly=${{steps.wildfly-nightly.outputs.wildfly-version}}' '-Dtest.report.dir=java21'
      - name: Test on ${{ matrix.os }} WildFly ${{steps.wildfly-nightly.outputs.wildfly-version}} - Java 17
        run:  |
          cd testsuite/integration-tests
          mvn ${{ env.MVN_ARGS }} verify '-Dtest.java.home=${{env.JAVA_HOME_17_X64}}${{env.JAVA_HOME_17_ARM64}}' '-Dversion.org.wildfly=${{steps.wildfly-nightly.outputs.wildfly-version}}' '-Dtest.report.dir=java17'
      - name: Upload test logs for failed run
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: failure-report-${{ matrix.os }}
          path: |
            **/failsafe-reports/**
            **/surefire-reports/**
            **/*.log

  additional-profiles:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        profile:
          - '-Pprovision-without-resteasy,without-jackson'

    steps:
      - uses: actions/checkout@v7
      - uses: wildfly-extras/wildfly-nightly-download@v1
        id: wildfly-nightly
      - name: Set up JDKs
        uses: actions/setup-java@v5.7.0
        with:
          distribution: 'temurin'
          cache: 'maven'
          java-version: |
            17
            21
            25
      - name: Build RESTEasy
        run: |
          ./mvnw ${{ env.MVN_ARGS }} clean install -DskipTests '-Dserver.version=${{steps.wildfly-nightly.outputs.wildfly-version}}'
      - name: Test with WildFly ${{steps.wildfly-nightly.outputs.wildfly-version}} - Java 25
        run:  |
          cd testsuite/integration-tests
          mvn ${{ env.MVN_ARGS }} verify ${{ matrix.profile }} '-Dserver.version=${{steps.wildfly-nightly.outputs.wildfly-version}}'
      - name: Test with WildFly ${{steps.wildfly-nightly.outputs.wildfly-version}} - Java 21
        run:  |
          cd testsuite/integration-tests
          mvn ${{ env.MVN_ARGS }} verify ${{ matrix.profile }} '-Dserver.version=${{steps.wildfly-nightly.outputs.wildfly-version}}' '-Dtest.java.home=${{env.JAVA_HOME_21_X64}}${{env.JAVA_HOME_21_ARM64}}' '-Dtest.report.dir=java21'
      - name: Test with WildFly ${{steps.wildfly-nightly.outputs.wildfly-version}} - Java 17
        run:  |
          cd testsuite/integration-tests
          mvn ${{ env.MVN_ARGS }} verify ${{ matrix.profile }} '-Dserver.version=${{steps.wildfly-nightly.outputs.wildfly-version}}' '-Dtest.java.home=${{env.JAVA_HOME_17_X64}}${{env.JAVA_HOME_17_ARM64}}' '-Dtest.report.dir=java17'
      - name: Upload test logs for failed run
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: failure-report
          path: |
            **/failsafe-reports/**
            **/surefire-reports/**
            **/*.log
